name: Make Docs
on:
  pull_request:
    branches: ["master", "dev"]
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/**'
      - 'docs/**'
  push:
    branches:
      - master
      - dev
      - docs
    paths:
      - '.github/workflows/make_docs.yml'
      - 'src/**'
      - 'docs/**'
    tags: '*'
  workflow_dispatch:
    
jobs:
  make_docs:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/workflows/make_docs.yml@master