name: Release Data

on:
  push:
    branches: ["master"]

jobs:
  release_artifacts:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/artifact_release.yaml@master
    secrets: inherit
    with:
      data_path: "data"