name: Release Data

on:
  push:
    branches: ["master"]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'
  pull_request:
    branches: ["master"]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'test/**'
      - 'Project.toml'

jobs:
  test:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/artifact_release.yml@master
    secrets: inherit
    with:
      RELEASE_TAG: ${{ env.RELEASE_TAG }}
      data_path: "data"