name: Release Data

on:
  workflow_dispatch:  # Manually trigger
  push:
    branches: ["master"]

jobs:
  release_artifacts:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/artifact_release.yml@master
    secrets: inherit
    with:
      data_path: "data"