name: Compat Helper
on:
  workflow_call:
jobs:
  CompatHelper:
    name: Compat Helper
    runs-on: ubuntu-latest
    steps:
      - name: "Add the FuseRegistry via Git"
        run: |
          using Pkg
          Pkg.Registry.add(RegistrySpec(url="https://github.com/ProjectTorreyPines/FuseRegistry.jl.git"))
          Pkg.Registry.add("General")
        shell: julia --color=yes {0}
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
        run: julia -e 'using CompatHelper; CompatHelper.main(;master_branch="master", use_existing_registries=true)'
