name: Make Docs
on:
  workflow_call:
    inputs:
      use_FuseRegistry:
        required: false
        default: true
        type: boolean
    
jobs:
  make_docs:
    name: Documentation
    permissions:
      actions: write
      contents: write
      statuses: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.x]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/cache@v2
      - name: "Add the FuseRegistry via Git"
        if: ${{ inputs.use_FuseRegistry }}
        run: |
          julia --project=docs/ -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/ProjectTorreyPines/FuseRegistry.jl.git")); Pkg.Registry.add("General")'
      - name: Install dependencies, build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: |
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'; julia --project=docs/ docs/make.jl
