name: Test

on:
  workflow_call:
    inputs:
      upload_artifact:
        required: false
        default: false
        type: boolean
      artifact_name:
        required: false
        default: None
        type: string
      artifact_path:
        required: false
        default: None
        type: string
      use_FuseRegistry:
        required: false
        default: true
        type: boolean
      use_dvc:
        required: false
        default: true
        type: boolean
      use_coverage:
        required: false
        default: false
        type: boolean

jobs:
  test:
    name: Test
    permissions:
      actions: write
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.x]
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v4
      - name: Add SSH keys
        if: ${{ inputs.use_dvc }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SOLPSTESTSAMPLES_SSH_KEY}}
            ${{ secrets.DVC_SSH_KEY }}
      - name: Configure ssh
        if: ${{ inputs.use_dvc }}
        run: |
          echo "${{ secrets.DVC_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.DVC_SSH_CONFIG }}" >> ~/.ssh/config
      - name: Install DVC
        uses: iterative/setup-dvc@v1
        if: ${{ inputs.use_dvc }}
        with:
          version: 3.58.0
      - name: DVC Pull
        if: ${{ inputs.use_dvc }}
        uses: nick-fields/retry@v3
        with:
          command: dvc pull
          max_attempts: 5
          retry_wait_seconds: 30
          timeout_minutes: 30
      - uses: julia-actions/cache@v2
      - name: "Add the FuseRegistry via Git"
        if: ${{ inputs.use_FuseRegistry }}
        run: |
          julia --project=. -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/ProjectTorreyPines/FuseRegistry.jl.git")); Pkg.Registry.add("General")'
      - uses: julia-actions/julia-runtest@v1
      - name: 'Upload Artifact'
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
      - name: 'Process Coverage'
        if: ${{ inputs.use_coverage }}
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage reports to Codecov
        if: ${{ inputs.use_coverage }}
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        # uses: codecov/codecov-action@v4
        # with:
        #   files: lcov.info