name: Test Reusable Workflow Test
on:
  workflow_dispatch:  # Manually trigger
  push:
    branches: master
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/test_test.yml'
  pull_request:
    branches: master
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/test_test.yml'

jobs:
  test_on_IMASggd:
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/test_reusable_workflow.yml@test_workflows
    secrets: inherit
    with:
      target_repo: ProjectTorreyPines/IMASggd.jl
      workflow_file: test.yml
      ref: master
      use_pat: true
