name: Test Reusable Workflow Format Check
on:
  workflow_dispatch:  # Manually trigger
  push:
    branches: master
    paths:
      - '.github/workflows/format_check.yml'
      - '.github/workflows/test_format_check.yml'
  pull_request:
    branches: master
    paths:
      - '.github/workflows/format_check.yml'
      - '.github/workflows/test_format_check.yml'

jobs:
  test_on_IMASggd:
    name: Testing format_check.yml on IMASggd
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/test_reusable_workflow.yml@master
    secrets: inherit
    with:
      target_repo: ProjectTorreyPines/IMASggd.jl
      workflow_file: format_check.yml
      ref: master
  test_on_SOLPS2imas:
    name: Testing format_check.yml on SOLPS2imas
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/test_reusable_workflow.yml@master
    secrets: inherit
    with:
      target_repo: ProjectTorreyPines/SOLPS2imas.jl
      workflow_file: format_check.yml
      ref: master
  test_on_FusionSyntheticDiagnostics:
    name: Testing format_check.yml on FusionSyntheticDiagnostics
    uses: ProjectTorreyPines/GitHubActionsWorkflows/.github/workflows/test_reusable_workflow.yml@master
    secrets: inherit
    with:
      target_repo: ProjectTorreyPines/FusionSyntheticDiagnostics.jl
      workflow_file: format_check.yml
      ref: master
