name: Test

on:
  workflow_call:
    inputs:
      upload_artifact:
        required: false
        default: false
        type: boolean
      artifact_name:
        required: false
        default: None
        type: string
      artifact_path:
        required: false
        default: None
        type: string
      use_dvc:
        required: false
        default: true
        type: boolean

jobs:
  test:
    name: Test
    permissions:
      actions: write
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.x]
        julia-arch: [x64]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@v4
      - name: Add SSH keys
        if: ${{ inputs.use_dvc }}
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SOLPSTESTSAMPLES_SSH_KEY}}
            ${{ secrets.DVC_SSH_KEY }}
      - name: Configure ssh
        if: ${{ inputs.use_dvc }}
        run: |
          echo "${{ secrets.DVC_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          echo "${{ secrets.DVC_SSH_CONFIG }}" >> ~/.ssh/config
      - uses: iterative/setup-dvc@v1
        if: ${{ inputs.use_dvc }}
      - name: DVC Pull
        if: ${{ inputs.use_dvc }}
        run: |
          dvc pull
      - uses: julia-actions/cache@v1
      - name: "Add the FuseRegistry via Git"
        env:
          PTP_READ_TOKEN: ${{ secrets.PTP_READ_TOKEN }}
        run: |
          rm -rf ~/.julia/registries/FuseRegistry
          julia -e 'using Pkg; Pkg.Registry.add(RegistrySpec(url="https://github.com/ProjectTorreyPines/FuseRegistry.jl.git")); Pkg.Registry.add("General")'
          find ~/.julia/registries/FuseRegistry -type f -name 'Package.toml' -exec sed -i "s|git@github.com:|https://project-torrey-pines:$PTP_READ_TOKEN@github.com/|g" {} +
      - uses: julia-actions/julia-runtest@v1
      - name: 'Upload Artifact'
        if: ${{ inputs.upload_artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
      # Not set up yet
      # - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v4
      #   with:
      #     files: lcov.info